//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/", ConfigurationName="InventoryService")]
public interface InventoryService
{
    
    // CODEGEN: Generating message contract since the operation getFilterValues is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="getFilterValues", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getFilterValuesResponse getFilterValues(getFilterValuesRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getInventoryLevels is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="getInventoryLevels", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getInventoryLevelsResponse getInventoryLevels(getInventoryLevelsRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class GetFilterValuesRequest
{
    
    private string wsVersionField;
    
    private string idField;
    
    private string passwordField;
    
    private string productIDField;
    
    private string productIDtypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string wsVersion
    {
        get
        {
            return this.wsVersionField;
        }
        set
        {
            this.wsVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
    public string productID
    {
        get
        {
            return this.productIDField;
        }
        set
        {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
    public string productIDtype
    {
        get
        {
            return this.productIDtypeField;
        }
        set
        {
            this.productIDtypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class GetFilterValuesReply
{
    
    private string productIDField;
    
    private string[] filterColorArrayField;
    
    private string[] filterSizeArrayField;
    
    private string[] filterSelectionArrayField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string productID
    {
        get
        {
            return this.productIDField;
        }
        set
        {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filterColor", DataType="token", IsNullable=false)]
    public string[] FilterColorArray
    {
        get
        {
            return this.filterColorArrayField;
        }
        set
        {
            this.filterColorArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filterSize", DataType="token", IsNullable=false)]
    public string[] FilterSizeArray
    {
        get
        {
            return this.filterSizeArrayField;
        }
        set
        {
            this.filterSizeArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filterSelection", DataType="token", IsNullable=false)]
    public string[] FilterSelectionArray
    {
        get
        {
            return this.filterSelectionArrayField;
        }
        set
        {
            this.filterSelectionArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
    public string errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFilterValuesRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/", Order=0)]
    public GetFilterValuesRequest GetFilterValuesRequest;
    
    public getFilterValuesRequest1()
    {
    }
    
    public getFilterValuesRequest1(GetFilterValuesRequest GetFilterValuesRequest)
    {
        this.GetFilterValuesRequest = GetFilterValuesRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFilterValuesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/", Order=0)]
    public GetFilterValuesReply GetFilterValuesReply;
    
    public getFilterValuesResponse()
    {
    }
    
    public getFilterValuesResponse(GetFilterValuesReply GetFilterValuesReply)
    {
        this.GetFilterValuesReply = GetFilterValuesReply;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class Request
{
    
    private string wsVersionField;
    
    private string idField;
    
    private string passwordField;
    
    private string productIDField;
    
    private string productIDtypeField;
    
    private string[] filterColorArrayField;
    
    private string[] filterSizeArrayField;
    
    private string[] filterSelectionArrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string wsVersion
    {
        get
        {
            return this.wsVersionField;
        }
        set
        {
            this.wsVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
    public string productID
    {
        get
        {
            return this.productIDField;
        }
        set
        {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
    public string productIDtype
    {
        get
        {
            return this.productIDtypeField;
        }
        set
        {
            this.productIDtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filterColor", DataType="token", IsNullable=false)]
    public string[] FilterColorArray
    {
        get
        {
            return this.filterColorArrayField;
        }
        set
        {
            this.filterColorArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filterSize", DataType="token", IsNullable=false)]
    public string[] FilterSizeArray
    {
        get
        {
            return this.filterSizeArrayField;
        }
        set
        {
            this.filterSizeArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filterSelection", DataType="token", IsNullable=false)]
    public string[] FilterSelectionArray
    {
        get
        {
            return this.filterSelectionArrayField;
        }
        set
        {
            this.filterSelectionArrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class Reply
{
    
    private string productIDField;
    
    private ReplyProductVariationInventory[] productVariationInventoryArrayField;
    
    private ReplyProductCompanionInventory[] productCompanionInventoryArrayField;
    
    private string errorMessageField;
    
    private string[] customMessageArrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string productID
    {
        get
        {
            return this.productIDField;
        }
        set
        {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductVariationInventory", IsNullable=false)]
    public ReplyProductVariationInventory[] ProductVariationInventoryArray
    {
        get
        {
            return this.productVariationInventoryArrayField;
        }
        set
        {
            this.productVariationInventoryArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductCompanionInventory", IsNullable=false)]
    public ReplyProductCompanionInventory[] ProductCompanionInventoryArray
    {
        get
        {
            return this.productCompanionInventoryArrayField;
        }
        set
        {
            this.productCompanionInventoryArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
    public string errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
    [System.Xml.Serialization.XmlArrayItemAttribute("customMessage", IsNullable=false)]
    public string[] CustomMessageArray
    {
        get
        {
            return this.customMessageArrayField;
        }
        set
        {
            this.customMessageArrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class ReplyProductVariationInventory
{
    
    private string partIDField;
    
    private string partDescriptionField;
    
    private string partBrandField;
    
    private string priceVarianceField;
    
    private string quantityAvailableField;
    
    private string attributeColorField;
    
    private string attributeSizeField;
    
    private string attributeSelectionField;
    
    private ReplyProductVariationInventoryAttributeFlex[] attributeFlexArrayField;
    
    private string customProductMessageField;
    
    private string entryTypeField;
    
    private System.DateTime validTimestampField;
    
    private bool validTimestampFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string partID
    {
        get
        {
            return this.partIDField;
        }
        set
        {
            this.partIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string partDescription
    {
        get
        {
            return this.partDescriptionField;
        }
        set
        {
            this.partDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string partBrand
    {
        get
        {
            return this.partBrandField;
        }
        set
        {
            this.partBrandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
    public string priceVariance
    {
        get
        {
            return this.priceVarianceField;
        }
        set
        {
            this.priceVarianceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
    public string quantityAvailable
    {
        get
        {
            return this.quantityAvailableField;
        }
        set
        {
            this.quantityAvailableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=5)]
    public string attributeColor
    {
        get
        {
            return this.attributeColorField;
        }
        set
        {
            this.attributeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=6)]
    public string attributeSize
    {
        get
        {
            return this.attributeSizeField;
        }
        set
        {
            this.attributeSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=7)]
    public string attributeSelection
    {
        get
        {
            return this.attributeSelectionField;
        }
        set
        {
            this.attributeSelectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
    [System.Xml.Serialization.XmlArrayItemAttribute("AttributeFlex", IsNullable=false)]
    public ReplyProductVariationInventoryAttributeFlex[] AttributeFlexArray
    {
        get
        {
            return this.attributeFlexArrayField;
        }
        set
        {
            this.attributeFlexArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string customProductMessage
    {
        get
        {
            return this.customProductMessageField;
        }
        set
        {
            this.customProductMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=10)]
    public string entryType
    {
        get
        {
            return this.entryTypeField;
        }
        set
        {
            this.entryTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public System.DateTime validTimestamp
    {
        get
        {
            return this.validTimestampField;
        }
        set
        {
            this.validTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validTimestampSpecified
    {
        get
        {
            return this.validTimestampFieldSpecified;
        }
        set
        {
            this.validTimestampFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class ReplyProductVariationInventoryAttributeFlex
{
    
    private string idField;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class ReplyProductCompanionInventory
{
    
    private string partIDField;
    
    private string partDescriptionField;
    
    private string partBrandField;
    
    private string priceField;
    
    private string quantityAvailableField;
    
    private string attributeColorField;
    
    private string attributeSizeField;
    
    private string attributeSelectionField;
    
    private ReplyProductCompanionInventoryAttributeFlex[] attributeFlexArrayField;
    
    private string customProductMessageField;
    
    private string entryTypeField;
    
    private System.DateTime validTimestampField;
    
    private bool validTimestampFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string partID
    {
        get
        {
            return this.partIDField;
        }
        set
        {
            this.partIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string partDescription
    {
        get
        {
            return this.partDescriptionField;
        }
        set
        {
            this.partDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string partBrand
    {
        get
        {
            return this.partBrandField;
        }
        set
        {
            this.partBrandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
    public string price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
    public string quantityAvailable
    {
        get
        {
            return this.quantityAvailableField;
        }
        set
        {
            this.quantityAvailableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=5)]
    public string attributeColor
    {
        get
        {
            return this.attributeColorField;
        }
        set
        {
            this.attributeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=6)]
    public string attributeSize
    {
        get
        {
            return this.attributeSizeField;
        }
        set
        {
            this.attributeSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=7)]
    public string attributeSelection
    {
        get
        {
            return this.attributeSelectionField;
        }
        set
        {
            this.attributeSelectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
    [System.Xml.Serialization.XmlArrayItemAttribute("AttributeFlex", IsNullable=false)]
    public ReplyProductCompanionInventoryAttributeFlex[] AttributeFlexArray
    {
        get
        {
            return this.attributeFlexArrayField;
        }
        set
        {
            this.attributeFlexArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string customProductMessage
    {
        get
        {
            return this.customProductMessageField;
        }
        set
        {
            this.customProductMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string entryType
    {
        get
        {
            return this.entryTypeField;
        }
        set
        {
            this.entryTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public System.DateTime validTimestamp
    {
        get
        {
            return this.validTimestampField;
        }
        set
        {
            this.validTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validTimestampSpecified
    {
        get
        {
            return this.validTimestampFieldSpecified;
        }
        set
        {
            this.validTimestampFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/")]
public partial class ReplyProductCompanionInventoryAttributeFlex
{
    
    private string idField;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventoryLevelsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/", Order=0)]
    public Request Request;
    
    public getInventoryLevelsRequest()
    {
    }
    
    public getInventoryLevelsRequest(Request Request)
    {
        this.Request = Request;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventoryLevelsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/InventoryService/1.0.0/", Order=0)]
    public Reply Reply;
    
    public getInventoryLevelsResponse()
    {
    }
    
    public getInventoryLevelsResponse(Reply Reply)
    {
        this.Reply = Reply;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface InventoryServiceChannel : InventoryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InventoryServiceClient : System.ServiceModel.ClientBase<InventoryService>, InventoryService
{
    
    public InventoryServiceClient()
    {
    }
    
    public InventoryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InventoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InventoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InventoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getFilterValuesResponse InventoryService.getFilterValues(getFilterValuesRequest1 request)
    {
        return base.Channel.getFilterValues(request);
    }
    
    public GetFilterValuesReply getFilterValues(GetFilterValuesRequest GetFilterValuesRequest)
    {
        getFilterValuesRequest1 inValue = new getFilterValuesRequest1();
        inValue.GetFilterValuesRequest = GetFilterValuesRequest;
        getFilterValuesResponse retVal = ((InventoryService)(this)).getFilterValues(inValue);
        return retVal.GetFilterValuesReply;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getInventoryLevelsResponse InventoryService.getInventoryLevels(getInventoryLevelsRequest request)
    {
        return base.Channel.getInventoryLevels(request);
    }
    
    public Reply getInventoryLevels(Request Request)
    {
        getInventoryLevelsRequest inValue = new getInventoryLevelsRequest();
        inValue.Request = Request;
        getInventoryLevelsResponse retVal = ((InventoryService)(this)).getInventoryLevels(inValue);
        return retVal.Reply;
    }
}
