//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LAN_AX2012_PRODEntities : DbContext
    {
        public LAN_AX2012_PRODEntities()
            : base("name=LAN_AX2012_PRODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LAN_VW_COLORDATA> LAN_VW_COLORDATA { get; set; }
        public virtual DbSet<LAN_VW_GETAVAILABLETOSHIP> LAN_VW_GETAVAILABLETOSHIP { get; set; }
        public virtual DbSet<LAN_VW_INVENTORY> LAN_VW_INVENTORY { get; set; }
        public virtual DbSet<LAN_VW_RETAILERS> LAN_VW_RETAILERS { get; set; }
        public virtual DbSet<LAN_VW_SIZEDATA> LAN_VW_SIZEDATA { get; set; }
        public virtual DbSet<LAN_VW_SKUMASTERDATA> LAN_VW_SKUMASTERDATA { get; set; }
        public virtual DbSet<LAN_VW_STYLE_ALTERNATES> LAN_VW_STYLE_ALTERNATES { get; set; }
    }
}
