//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LAN_AX2012_PRODEntities1 : DbContext
    {
        public LAN_AX2012_PRODEntities1()
            : base("name=LAN_AX2012_PRODEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<lan_sp_B2B_Reports_CustomerOpenItems_Result> lan_sp_B2B_Reports_CustomerOpenItems(string accountStore)
        {
            var accountStoreParameter = accountStore != null ?
                new ObjectParameter("AccountStore", accountStore) :
                new ObjectParameter("AccountStore", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lan_sp_B2B_Reports_CustomerOpenItems_Result>("lan_sp_B2B_Reports_CustomerOpenItems", accountStoreParameter);
        }
    
        public virtual ObjectResult<lan_sp_B2B_Reports_CustomerOpenItems_JG_Result> lan_sp_B2B_Reports_CustomerOpenItems_JG(string accountStore)
        {
            var accountStoreParameter = accountStore != null ?
                new ObjectParameter("AccountStore", accountStore) :
                new ObjectParameter("AccountStore", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lan_sp_B2B_Reports_CustomerOpenItems_JG_Result>("lan_sp_B2B_Reports_CustomerOpenItems_JG", accountStoreParameter);
        }
    
        public virtual ObjectResult<lan_sp_B2B_Reports_InvoiceSummary_Result> lan_sp_B2B_Reports_InvoiceSummary(string accountStore)
        {
            var accountStoreParameter = accountStore != null ?
                new ObjectParameter("AccountStore", accountStore) :
                new ObjectParameter("AccountStore", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lan_sp_B2B_Reports_InvoiceSummary_Result>("lan_sp_B2B_Reports_InvoiceSummary", accountStoreParameter);
        }
    
        public virtual ObjectResult<lan_sp_B2B_Reports_ShipmentsByAccount_Result> lan_sp_B2B_Reports_ShipmentsByAccount(string accountID, string storeID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string orderNumber, string pONumber)
        {
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var storeIDParameter = storeID != null ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var orderNumberParameter = orderNumber != null ?
                new ObjectParameter("OrderNumber", orderNumber) :
                new ObjectParameter("OrderNumber", typeof(string));
    
            var pONumberParameter = pONumber != null ?
                new ObjectParameter("PONumber", pONumber) :
                new ObjectParameter("PONumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lan_sp_B2B_Reports_ShipmentsByAccount_Result>("lan_sp_B2B_Reports_ShipmentsByAccount", accountIDParameter, storeIDParameter, startDateParameter, endDateParameter, orderNumberParameter, pONumberParameter);
        }
    
        public virtual ObjectResult<lan_sp_B2B_Reports_ShipmentsByOrderNumber_Result> lan_sp_B2B_Reports_ShipmentsByOrderNumber(string accountID, string storeID, string orderNumber)
        {
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var storeIDParameter = storeID != null ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(string));
    
            var orderNumberParameter = orderNumber != null ?
                new ObjectParameter("OrderNumber", orderNumber) :
                new ObjectParameter("OrderNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lan_sp_B2B_Reports_ShipmentsByOrderNumber_Result>("lan_sp_B2B_Reports_ShipmentsByOrderNumber", accountIDParameter, storeIDParameter, orderNumberParameter);
        }
    
        public virtual ObjectResult<LAN_SP_B2B_SALESLINES_Result> LAN_SP_B2B_SALESLINES(string orderID)
        {
            var orderIDParameter = orderID != null ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LAN_SP_B2B_SALESLINES_Result>("LAN_SP_B2B_SALESLINES", orderIDParameter);
        }
    
        public virtual ObjectResult<LAN_SP_B2B_SUBMITTEDORDERBYORDERID_Result> LAN_SP_B2B_SUBMITTEDORDERBYORDERID(string orderId)
        {
            var orderIdParameter = orderId != null ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LAN_SP_B2B_SUBMITTEDORDERBYORDERID_Result>("LAN_SP_B2B_SUBMITTEDORDERBYORDERID", orderIdParameter);
        }
    
        public virtual ObjectResult<LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT_Result> LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT(string account)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT_Result>("LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT", accountParameter);
        }
    
        public virtual ObjectResult<lan_sp_B2B_SubmittedOrdersByAccount_v2_Result> lan_sp_B2B_SubmittedOrdersByAccount_v2(string account, Nullable<int> page, Nullable<int> size, ObjectParameter totalRecords)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("Size", size) :
                new ObjectParameter("Size", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lan_sp_B2B_SubmittedOrdersByAccount_v2_Result>("lan_sp_B2B_SubmittedOrdersByAccount_v2", accountParameter, pageParameter, sizeParameter, totalRecords);
        }
    
        public virtual ObjectResult<LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT60days_Result> LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT60days(string account)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT60days_Result>("LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNT60days", accountParameter);
        }
    
        public virtual ObjectResult<lan_sp_B2B_SubmittedOrdersByAccountByDateRange_Result> lan_sp_B2B_SubmittedOrdersByAccountByDateRange(string account, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lan_sp_B2B_SubmittedOrdersByAccountByDateRange_Result>("lan_sp_B2B_SubmittedOrdersByAccountByDateRange", accountParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<LAN_SP_B2B_SUBMITTEDORDERBYORDERIDWITHSTATUS_Result> LAN_SP_B2B_SUBMITTEDORDERBYORDERIDWITHSTATUS(string orderId)
        {
            var orderIdParameter = orderId != null ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LAN_SP_B2B_SUBMITTEDORDERBYORDERIDWITHSTATUS_Result>("LAN_SP_B2B_SUBMITTEDORDERBYORDERIDWITHSTATUS", orderIdParameter);
        }
    
        public virtual ObjectResult<LAN_SP_B2B_SUBMITTEDORDERBYPONUMBER_Result> LAN_SP_B2B_SUBMITTEDORDERBYPONUMBER(string orderId)
        {
            var orderIdParameter = orderId != null ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LAN_SP_B2B_SUBMITTEDORDERBYPONUMBER_Result>("LAN_SP_B2B_SUBMITTEDORDERBYPONUMBER", orderIdParameter);
        }
    
        public virtual ObjectResult<LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNTWITHSTATUS_Result> LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNTWITHSTATUS(string account)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNTWITHSTATUS_Result>("LAN_SP_B2B_SUBMITTEDORDERSBYACCOUNTWITHSTATUS", accountParameter);
        }
    }
}
