//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", ConfigurationName="OrderStatusService")]
public interface OrderStatusService
{
    
    // CODEGEN: Generating message contract since the operation getOrderStatusDetails is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="getOrderStatusDetails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getOrderStatusDetailsResponse1 getOrderStatusDetails(getOrderStatusDetailsRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getOrderStatusTypes is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="getOrderStatusTypes", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getOrderStatusTypesResponse1 getOrderStatusTypes(getOrderStatusTypesRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusDetailsRequest
{
    
    private string wsVersionField;
    
    private string idField;
    
    private string passwordField;
    
    private int queryTypeField;
    
    private string referenceNumberField;
    
    private System.Nullable<System.DateTime> statusTimeStampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string wsVersion
    {
        get
        {
            return this.wsVersionField;
        }
        set
        {
            this.wsVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int queryType
    {
        get
        {
            return this.queryTypeField;
        }
        set
        {
            this.queryTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
    public string referenceNumber
    {
        get
        {
            return this.referenceNumberField;
        }
        set
        {
            this.referenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
    public System.Nullable<System.DateTime> statusTimeStamp
    {
        get
        {
            return this.statusTimeStampField;
        }
        set
        {
            this.statusTimeStampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusDetailsResponse
{
    
    private GetOrderStatusDetailsResponseOrderStatus[] orderStatusArrayField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OrderStatus", IsNullable=false)]
    public GetOrderStatusDetailsResponseOrderStatus[] OrderStatusArray
    {
        get
        {
            return this.orderStatusArrayField;
        }
        set
        {
            this.orderStatusArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusDetailsResponseOrderStatus
{
    
    private string purchaseOrderNumberField;
    
    private GetOrderStatusDetailsResponseOrderStatusOrderStatusDetail[] orderStatusDetailArrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string purchaseOrderNumber
    {
        get
        {
            return this.purchaseOrderNumberField;
        }
        set
        {
            this.purchaseOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OrderStatusDetail", IsNullable=false)]
    public GetOrderStatusDetailsResponseOrderStatusOrderStatusDetail[] OrderStatusDetailArray
    {
        get
        {
            return this.orderStatusDetailArrayField;
        }
        set
        {
            this.orderStatusDetailArrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusDetailsResponseOrderStatusOrderStatusDetail
{
    
    private string factoryOrderNumberField;
    
    private GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailStatusID statusIDField;
    
    private string statusNameField;
    
    private System.Nullable<System.DateTime> expectedShipDateField;
    
    private bool expectedShipDateFieldSpecified;
    
    private System.Nullable<System.DateTime> expectedDeliveryDateField;
    
    private bool expectedDeliveryDateFieldSpecified;
    
    private GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondTo[] responseToArrayField;
    
    private string additionalExplanationField;
    
    private bool responseRequiredField;
    
    private bool responseRequiredFieldSpecified;
    
    private System.DateTime validTimestampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string factoryOrderNumber
    {
        get
        {
            return this.factoryOrderNumberField;
        }
        set
        {
            this.factoryOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailStatusID statusID
    {
        get
        {
            return this.statusIDField;
        }
        set
        {
            this.statusIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string statusName
    {
        get
        {
            return this.statusNameField;
        }
        set
        {
            this.statusNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public System.Nullable<System.DateTime> expectedShipDate
    {
        get
        {
            return this.expectedShipDateField;
        }
        set
        {
            this.expectedShipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expectedShipDateSpecified
    {
        get
        {
            return this.expectedShipDateFieldSpecified;
        }
        set
        {
            this.expectedShipDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public System.Nullable<System.DateTime> expectedDeliveryDate
    {
        get
        {
            return this.expectedDeliveryDateField;
        }
        set
        {
            this.expectedDeliveryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expectedDeliveryDateSpecified
    {
        get
        {
            return this.expectedDeliveryDateFieldSpecified;
        }
        set
        {
            this.expectedDeliveryDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
    [System.Xml.Serialization.XmlArrayItemAttribute("RespondTo", IsNullable=false)]
    public GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondTo[] ResponseToArray
    {
        get
        {
            return this.responseToArrayField;
        }
        set
        {
            this.responseToArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string additionalExplanation
    {
        get
        {
            return this.additionalExplanationField;
        }
        set
        {
            this.additionalExplanationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool responseRequired
    {
        get
        {
            return this.responseRequiredField;
        }
        set
        {
            this.responseRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool responseRequiredSpecified
    {
        get
        {
            return this.responseRequiredFieldSpecified;
        }
        set
        {
            this.responseRequiredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public System.DateTime validTimestamp
    {
        get
        {
            return this.validTimestampField;
        }
        set
        {
            this.validTimestampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public enum GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailStatusID
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    None,

    [System.Xml.Serialization.XmlEnumAttribute("1")]
    OpenOrder,

    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Delivered,

    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Invoiced,

    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Canceled,


}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusDetailsResponseOrderStatusOrderStatusDetailRespondTo
{
    
    private string nameField;
    
    private string emailAddressField;
    
    private string phoneNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string emailAddress
    {
        get
        {
            return this.emailAddressField;
        }
        set
        {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string phoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getOrderStatusDetailsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
    public GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest;
    
    public getOrderStatusDetailsRequest1()
    {
    }
    
    public getOrderStatusDetailsRequest1(GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest)
    {
        this.GetOrderStatusDetailsRequest = GetOrderStatusDetailsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getOrderStatusDetailsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
    public GetOrderStatusDetailsResponse GetOrderStatusDetailsResponse;
    
    public getOrderStatusDetailsResponse1()
    {
    }
    
    public getOrderStatusDetailsResponse1(GetOrderStatusDetailsResponse GetOrderStatusDetailsResponse)
    {
        this.GetOrderStatusDetailsResponse = GetOrderStatusDetailsResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusTypesRequest
{
    
    private string wsVersionField;
    
    private string idField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string wsVersion
    {
        get
        {
            return this.wsVersionField;
        }
        set
        {
            this.wsVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusTypesResponse
{
    
    private GetOrderStatusTypesResponseStatus[] statusArrayField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Status", IsNullable=false)]
    public GetOrderStatusTypesResponseStatus[] StatusArray
    {
        get
        {
            return this.statusArrayField;
        }
        set
        {
            this.statusArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/")]
public partial class GetOrderStatusTypesResponseStatus
{
    
    private int idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getOrderStatusTypesRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
    public GetOrderStatusTypesRequest GetOrderStatusTypesRequest;
    
    public getOrderStatusTypesRequest1()
    {
    }
    
    public getOrderStatusTypesRequest1(GetOrderStatusTypesRequest GetOrderStatusTypesRequest)
    {
        this.GetOrderStatusTypesRequest = GetOrderStatusTypesRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getOrderStatusTypesResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/", Order=0)]
    public GetOrderStatusTypesResponse GetOrderStatusTypesResponse;
    
    public getOrderStatusTypesResponse1()
    {
    }
    
    public getOrderStatusTypesResponse1(GetOrderStatusTypesResponse GetOrderStatusTypesResponse)
    {
        this.GetOrderStatusTypesResponse = GetOrderStatusTypesResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface OrderStatusServiceChannel : OrderStatusService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OrderStatusServiceClient : System.ServiceModel.ClientBase<OrderStatusService>, OrderStatusService
{
    
    public OrderStatusServiceClient()
    {
    }
    
    public OrderStatusServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public OrderStatusServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OrderStatusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OrderStatusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getOrderStatusDetailsResponse1 OrderStatusService.getOrderStatusDetails(getOrderStatusDetailsRequest1 request)
    {
        return base.Channel.getOrderStatusDetails(request);
    }
    
    public GetOrderStatusDetailsResponse getOrderStatusDetails(GetOrderStatusDetailsRequest GetOrderStatusDetailsRequest)
    {
        getOrderStatusDetailsRequest1 inValue = new getOrderStatusDetailsRequest1();
        inValue.GetOrderStatusDetailsRequest = GetOrderStatusDetailsRequest;
        getOrderStatusDetailsResponse1 retVal = ((OrderStatusService)(this)).getOrderStatusDetails(inValue);
        return retVal.GetOrderStatusDetailsResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getOrderStatusTypesResponse1 OrderStatusService.getOrderStatusTypes(getOrderStatusTypesRequest1 request)
    {
        return base.Channel.getOrderStatusTypes(request);
    }
    
    public GetOrderStatusTypesResponse getOrderStatusTypes(GetOrderStatusTypesRequest GetOrderStatusTypesRequest)
    {
        getOrderStatusTypesRequest1 inValue = new getOrderStatusTypesRequest1();
        inValue.GetOrderStatusTypesRequest = GetOrderStatusTypesRequest;
        getOrderStatusTypesResponse1 retVal = ((OrderStatusService)(this)).getOrderStatusTypes(inValue);
        return retVal.GetOrderStatusTypesResponse;
    }
}
