//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_VW_STYLE_ALTERNATES
    {
        public string StyleCode { get; set; }
        public string StyleCodeAssigned { get; set; }
        public string LookUpType { get; set; }
    }
}
