//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_VW_RETAILERS
    {
        public string ACCOUNT { get; set; }
        public string STORENAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public string WEBSITE { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string TERMS { get; set; }
        public string SHIPVIA { get; set; }
        public string AUTHORIZED { get; set; }
        public string RESTRICTED { get; set; }
        public int MINSHIPQTY { get; set; }
        public string SHIPRULE { get; set; }
        public Nullable<bool> ISINTERNATIONAL { get; set; }
        public int ISBLOCKED { get; set; }
        public string CLASSIFICATIONID { get; set; }
    }
}
