//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_VW_SIZEDATA
    {
        public string ITEMID { get; set; }
        public string InventSizeId { get; set; }
        public Nullable<int> SUNTAFSIZESEQ { get; set; }
        public string NAME { get; set; }
        public string Expr1 { get; set; }
        public string DATAAREAID { get; set; }
        public long PARTITION { get; set; }
    }
}
