//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_VW_INVENTORY
    {
        public string ITEMID { get; set; }
        public string INVENTCOLORID { get; set; }
        public string INVENTSIZEID { get; set; }
        public Nullable<decimal> GETQTYPHYSICAL { get; set; }
        public Nullable<decimal> GETQTYCURRENTOPENORDER { get; set; }
        public Nullable<decimal> GETQTYAVAILABLE { get; set; }
        public Nullable<decimal> GETQTYRESERVE { get; set; }
    }
}
