//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_VW_SKUMASTERDATA
    {
        public string ITEMID { get; set; }
        public long PRODUCT { get; set; }
        public string ItemName { get; set; }
        public string ITEMGROUPID { get; set; }
        public string INVENTSIZEID { get; set; }
        public string INVENTCOLORID { get; set; }
        public int SIZESEQ { get; set; }
        public int COLORSEQ { get; set; }
        public string COLORNAME { get; set; }
        public string INVENTDIMID { get; set; }
        public string SUNTAFITEMSTATUS { get; set; }
        public string ITEMBARCODE { get; set; }
        public decimal LANCUBEFACTOR { get; set; }
        public string LANPRODUCTSEGMENT { get; set; }
        public decimal LANWEIGHT { get; set; }
        public string DATAAREAID { get; set; }
        public long PARTITION { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
    }
}
