//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau_PromoStandards
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_VW_COLORDATA
    {
        public string ITEMID { get; set; }
        public string InventColorId { get; set; }
        public Nullable<int> SUNTAFCOLORSEQ { get; set; }
        public string SUNTAFSEASONCODE { get; set; }
        public string NAME { get; set; }
        public string LANCARETYPEID { get; set; }
        public string LANFABRICDIRECTIONID { get; set; }
        public Nullable<int> LANHTSCATEGORY { get; set; }
        public string LANHTSCODE { get; set; }
        public string LANHTSCODEEXPORT { get; set; }
        public string LANHTSCODEINT { get; set; }
        public string LANPRINTGROUPID { get; set; }
        public Nullable<int> LANWEBDISPLAY { get; set; }
        public string DATAAREAID { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
